// src/views/Settings/dialogs/LaunchOptionsDialog.vue
<template>
    <Dialog :open="isLaunchOptionsDialogVisible" @update:open="(open) => (open ? null : closeDialog())">
        <DialogContent>
            <DialogHeader>
                <DialogTitle>{{ t('dialog.launch_options.header') }}</DialogTitle>
            </DialogHeader>
            <div class="text-xs">
                {{ t('dialog.launch_options.description') }} <br />
                {{ t('dialog.launch_options.example') }}
                <div>--fps=144</div>
                <div>--enable-debug-gui</div>
                <div>--enable-sdk-log-levels</div>
                <div>--enable-udon-debug-logging</div>
            </div>

            <InputGroupTextareaField
                v-model="launchOptionsDialog.launchArguments"
                :autosize="{ minRows: 2, maxRows: 5 }"
                :rows="2"
                placeholder="e.g. --fps=144 --enable-sdk-log-levels"
                input-class="resize-none" />

            <div class="text-sm">
                {{ t('dialog.launch_options.path_override') }}
            </div>

            <InputGroupTextareaField
                v-model="launchOptionsDialog.vrcLaunchPathOverride"
                placeholder="C:\Program Files (x86)\Steam\steamapps\common\VRChat"
                :rows="1"
                class="mb-4"
                spellcheck="false"
                data-gramm="false"
                input-class="resize-none min-h-0" />

            <DialogFooter>
                <div class="flex items-center justify-between w-full">
                    <div>
                        <Button
                            variant="outline"
                            class="mr-2"
                            @click="openExternalLink('https://docs.vrchat.com/docs/launch-options')">
                            {{ t('dialog.launch_options.vrchat_docs') }}
                        </Button>
                        <Button
                            variant="outline"
                            @click="openExternalLink('https://docs.unity3d.com/Manual/CommandLineArguments.html')">
                            {{ t('dialog.launch_options.unity_manual') }}
                        </Button>
                    </div>
                    <Button @click="updateLaunchOptions">
                        {{ t('dialog.launch_options.save') }}
                    </Button>
                </div>
            </DialogFooter>
        </DialogContent>
    </Dialog>
</template>

<script setup>
    import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
    import { computed, ref } from 'vue';
    import { Button } from '@/components/ui/button';
    import { InputGroupTextareaField } from '@/components/ui/input-group';
    import { storeToRefs } from 'pinia';
    import { toast } from 'vue-sonner';
    import { useI18n } from 'vue-i18n';

    import { Badge } from '../../../components/ui/badge';
    import { openExternalLink } from '../../../shared/utils';
    import { useLaunchStore } from '../../../stores';

    import configRepository from '../../../services/config';

    const { t } = useI18n();

    const launchStore = useLaunchStore();
    const { isLaunchOptionsDialogVisible } = storeToRefs(launchStore);

    const launchOptionsDialog = ref({
        launchArguments: '',
        vrcLaunchPathOverride: ''
    });



    function init() {
        configRepository
            .getString('launchArguments')
            .then((launchArguments) => (launchOptionsDialog.value.launchArguments = launchArguments));

        configRepository.getString('vrcLaunchPathOverride').then((vrcLaunchPathOverride) => {
            if (vrcLaunchPathOverride === null || vrcLaunchPathOverride === 'null') {
                launchOptionsDialog.value.vrcLaunchPathOverride = '';
                configRepository.setString('vrcLaunchPathOverride', '');
            } else {
                launchOptionsDialog.value.vrcLaunchPathOverride = vrcLaunchPathOverride;
            }
        });
    }

    // created
    init();

    function updateLaunchOptions() {
        const D = launchOptionsDialog.value;
        D.launchArguments = String(D.launchArguments).replace(/\s+/g, ' ').trim();
        configRepository.setString('launchArguments', D.launchArguments);
        if (
            D.vrcLaunchPathOverride &&
            D.vrcLaunchPathOverride.endsWith('.exe') &&
            !D.vrcLaunchPathOverride.endsWith('launch.exe')
        ) {
            toast.error(t('message.launch.invalid_path'));
            return;
        }
        configRepository.setString('vrcLaunchPathOverride', D.vrcLaunchPathOverride);
        toast.success('Updated launch options');
        closeDialog();
    }

    function closeDialog() {
        isLaunchOptionsDialogVisible.value = false;
    }
</script>

// src/components/hosts/system-dialogs/LaunchOptionsDialog.jsx
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';

import { userFacingErrorMessage } from '@/lib/errorDisplay.js';
import { backend } from '@/platform/index.js';
import { configRepository } from '@/repositories/index.js';
import { Button } from '@/ui/shadcn/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle
} from '@/ui/shadcn/dialog';
import { Field, FieldGroup, FieldLabel } from '@/ui/shadcn/field';
import { Input } from '@/ui/shadcn/input';
import { Textarea } from '@/ui/shadcn/textarea';

export function LaunchOptionsDialog({ open, onOpenChange }) {
    const { t } = useTranslation();
    const [launchArguments, setLaunchArguments] = useState('');
    const [vrcLaunchPathOverride, setVrcLaunchPathOverride] = useState('');
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (!open) {
            return undefined;
        }

        let active = true;
        setLoading(true);
        Promise.all([
            configRepository.getString('launchArguments', ''),
            configRepository.getString('vrcLaunchPathOverride', '')
        ])
            .then(([nextLaunchArguments, nextLaunchPath]) => {
                if (!active) {
                    return;
                }
                const normalizedLaunchPath =
                    nextLaunchPath && nextLaunchPath !== 'null'
                        ? nextLaunchPath
                        : '';
                setLaunchArguments(nextLaunchArguments || '');
                setVrcLaunchPathOverride(normalizedLaunchPath);
                if (nextLaunchPath === 'null') {
                    void configRepository.setString(
                        'vrcLaunchPathOverride',
                        ''
                    );
                }
            })
            .catch((error) => {
                toast.error(
                    userFacingErrorMessage(
                        error,
                        t(
                            'host.system_dialogs.toast.failed_to_load_launch_options'
                        )
                    )
                );
            })
            .finally(() => {
                if (active) {
                    setLoading(false);
                }
            });

        return () => {
            active = false;
        };
    }, [open]);

    async function handleSave() {
        const normalizedArguments = String(launchArguments)
            .replace(/\s+/g, ' ')
            .trim();
        if (
            vrcLaunchPathOverride &&
            vrcLaunchPathOverride.endsWith('.exe') &&
            !vrcLaunchPathOverride.endsWith('launch.exe')
        ) {
            toast.error(t('message.launch.invalid_path'));
            return;
        }

        setLoading(true);
        try {
            await Promise.all([
                configRepository.setString(
                    'launchArguments',
                    normalizedArguments
                ),
                configRepository.setString(
                    'vrcLaunchPathOverride',
                    vrcLaunchPathOverride
                )
            ]);
            setLaunchArguments(normalizedArguments);
            toast.success(t('dialog.system.success.updated_launch_options'));
            onOpenChange(false);
        } catch (error) {
            toast.error(
                userFacingErrorMessage(
                    error,
                    t(
                        'host.system_dialogs.toast.failed_to_save_launch_options'
                    )
                )
            );
        } finally {
            setLoading(false);
        }
    }

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent>
                <DialogHeader>
                    <DialogTitle>
                        {t('dialog.launch_options.header')}
                    </DialogTitle>
                    <DialogDescription>
                        {t('dialog.launch_options.description')}{' '}
                        {t('dialog.launch_options.example')}
                    </DialogDescription>
                </DialogHeader>
                <FieldGroup>
                    <div className="bg-muted/30 text-muted-foreground rounded-md border p-3 text-xs">
                        <div>{t('dialog.system.label.fps_144')}</div>
                        <div>
                            {t('dialog.system.action.enable_debug_gui')}
                        </div>
                        <div>
                            {t('dialog.system.action.enable_sdk_log_levels')}
                        </div>
                        <div>
                            {t(
                                'dialog.system.action.enable_udon_debug_logging'
                            )}
                        </div>
                    </div>
                    <Field>
                        <FieldLabel htmlFor="launch-options-arguments">
                            {t('dialog.launch_options.header')}
                        </FieldLabel>
                        <Textarea
                            id="launch-options-arguments"
                            rows={3}
                            value={launchArguments}
                            placeholder="e.g. --fps=144 --enable-sdk-log-levels"
                            onChange={(event) =>
                                setLaunchArguments(event.target.value)
                            }
                        />
                    </Field>
                    <Field>
                        <FieldLabel htmlFor="launch-options-path-override">
                            {t('dialog.launch_options.path_override')}
                        </FieldLabel>
                        <Input
                            id="launch-options-path-override"
                            value={vrcLaunchPathOverride}
                            placeholder="C:\\Program Files (x86)\\Steam\\steamapps\\common\\VRChat\\launch.exe"
                            spellCheck={false}
                            onChange={(event) =>
                                setVrcLaunchPathOverride(event.target.value)
                            }
                        />
                    </Field>
                </FieldGroup>
                <DialogFooter>
                    <Button
                        type="button"
                        variant="outline"
                        onClick={() =>
                            void backend.app.OpenLink(
                                'https://docs.vrchat.com/docs/launch-options'
                            )
                        }
                    >
                        {t('dialog.launch_options.vrchat_docs')}
                    </Button>
                    <Button
                        type="button"
                        variant="outline"
                        onClick={() =>
                            void backend.app.OpenLink(
                                'https://docs.unity3d.com/Manual/CommandLineArguments.html'
                            )
                        }
                    >
                        {t('dialog.launch_options.unity_manual')}
                    </Button>
                    <Button
                        type="button"
                        disabled={loading}
                        onClick={() => void handleSave()}
                    >
                        {t('dialog.launch_options.save')}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
